### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by filipekiss** [roxma/nvim-cm-tern#13]
Hey, @roxma! First of all, thanks for the amazing NCM plugin. I'm loving it.

Recently, I've been trying to make my JavaScript completion work with tern, but I haven't had any success.

I've browsed the issues here and tried everything you suggested already but I can't get it to work.

The tern command is indeed invoked when I run `nvim` and the plugin is loaded, but if I type `document.` no autocomplete is shown. But if I install `tern_for_vim` and call the omnifunc, `document.` will allow me to select things like `document.querySelector`.

I really want to make this work, but I'm all out of ideas on what should I do.

Here's my relevant vim config, let me know if you need anything else:

```Viml
" [...]
    if has('nvim')
        Plug 'roxma/nvim-completion-manager'
        Plug 'roxma/nvim-cm-tern', { 'do': 'yarn install' }
    endif
" [...]
  if has('nvim')
        let g:UltiSnipsExpandTrigger		= "<Plug>(ultisnips_expand)"
        let g:UltiSnipsJumpForwardTrigger	= "<c-j>"
        let g:UltiSnipsJumpBackwardTrigger	= "<c-k>"
        let g:UltiSnipsRemoveSelectModeMappings = 0
        inoremap <silent> <c-u> <c-r>=cm#sources#ultisnips#trigger_or_popup("\<Plug>(ultisnips_expand)")<cr>
        inoremap <expr> <c-j> pumvisible() ? "\<C-n>" : "\<c-j>"
        inoremap <expr> <c-k> pumvisible() ? "\<C-p>" : "\<c-k>"
        xmap <c-u> <Plug>(ultisnips_expand)
        smap <c-u> <Plug>(ultisnips_expand)
    endif

" [...]
let g:cm_complete_delay = 0
let g:cm_sources_override = {
        \ 'cm-tags': {'enable':0}
        \ }
```

Thanks again for the great plugin, and I hope you can spot what I'm missing!

**Comment by roxma** [comment]
`:help NCM-trouble-shooting` generate the log files and see if we could get some useful informantion there.

**Comment by filipekiss** [comment]
Generated the logs and, as soon as I try to complete some javascript, this pops-up:

```
Traceback (most recent call last):
  File "/Users/filipekiss/.vim/plugged/nvim-cm-tern/pythonx/cm_sources/cm_tern.py", line 90, in request
    req = self._opener.open("http://127.0.0.1:" + str(self._port) + "/", payload)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

I ran `ps aux | grep tern` to see if it was running and this is the result:

```
filipekiss       65734   0.0  0.4  4939532  37140   ??  SN    1:34PM   0:00.28 node /Users/filipekiss/.vim/plugged/nvim-cm-tern/node_modules/tern/bin/tern --persistent --no-port-file
filipekiss       65730   0.0  0.3  4282228  21616   ??  SN    1:34PM   0:00.23 /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python /Users/filipekiss/.vim/plugged/nvim-completion-manager/pythonx/cm_start.py channel cm-tern cm_sources.cm_tern /var/folders/hv/vmxh86rx62z0d62c6sk3bp9c0000gn/T/nvim4lcKxH/0
```

**Comment by roxma** [comment]
I cannot reproduce the issue.

The HTTP post body is in the log files.

You could use `node /Users/filipekiss/.vim/plugged/nvim-cm-tern/node_modules/tern/bin/tern --persistent --no-port-file` to start another tern instance, then post the same request to it and see what happens.

**Comment by filipekiss** [comment]
Well, I tried to replicate it and now it's working and I've changed nothing. Not sure what's going on here. I think this may be closed for now but if it ever happens again, I'll check the post body in the log files and update this issue! Thank you, @roxma.
