### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by markonm** [roxma/nvim-cm-tern#2]
I installed this source with vim-plug and did `npm install` but I don't see any completions being showed.

**Comment by markonm** [comment]
Thank you! It works now, but It's very slow. Completions appear with delay of couple of seconds. On WSL completions appear instantly in Vim8 and Neovim.

**Comment by roxma** [comment]
Is this always slow? Or slow in seconds after you start  neovim/vim8?

**Comment by markonm** [comment]
It's always slow. Delay is about 2 seconds. In gvim and in vim.
