### ISSUE TITLE
es6 keywords

### ISSUE THREAD

**Issue by robinknaapen** [roxma/nvim-cm-tern#6]
So i'm having trouble with es6 completion. When using es6 keywords the autocompetion is not showing, for example.

```javascript
let someLongVariableName = "bar"
some // When trying to auto complete this nothing shows up
```

The same issue occurs with using `const` `import foo from 'bar'`

I made a `.tern-config` in my home folder in order to enable es6 syntax. this doesn't help

```json
{
    "ecmaVersion": 6
}
```

![](https://ss.kumori.moe/file/2017-08-02-23:43:21.png)

![](https://ss.kumori.moe/file/2017-08-02-23:43:58.png)

**Comment by roxma** [comment]
Wired, I cannot reproduce this issue

Your first example with your `.tern-config` works on my side.

**Comment by robinknaapen** [comment]
I see. I will look into this as soon as I get home.

**Comment by robinknaapen** [comment]
I've tried it again, I couldn't bring to work though. So I tried the alternative, I can confirm that it works with deoplete + deoplete-tern. I don't know the cause of the issue with nvim-cm.

**Comment by robinknaapen** [comment]
I've found the issue... I trigger my completion manual. 

`let g:cm_auto_popup = 0`

This results in tern's completion not showing
