### ISSUE TITLE
doesn't complete filename

### ISSUE THREAD

**Issue by davidsu** [roxma/nvim-cm-tern#9]
with deoplete-tern I get tern to give me suggestion for `require('../`... These suggestions are better than `cm-filepath` since they are exact and noise-free(only the requireable files appear)

EDIT: funny enough if I type `require('../<C-x><C-o>'` than I do get the suggestions from tern. I don't quite understand what's going on there.

EDIT: I understand... `require('../<C-x><C-o>'` works because tern-for-vim set the omnifunc to tern#complete for `filetype=javascript`

**Comment by roxma** [comment]
I will look into this ASAP.
